name: bestwaytoproceed
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.11.0+1
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

